# Generated by Django 3.2.4 on 2021-07-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210717_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, default='djangodbmodelsfieldscharfield', null=True),
        ),
    ]
