# Generated by Django 3.2.5 on 2021-08-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_category_post_postcomment_project_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
