# Generated by Django 3.2.5 on 2021-08-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210824_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pictures/blank-profile-picture.png', null=True, upload_to='profile_pictures'),
        ),
    ]
