# Generated by Django 3.2.5 on 2021-08-31 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210831_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='company',
            name='description',
        ),
        migrations.RemoveField(
            model_name='company',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='company',
            name='position',
        ),
        migrations.RemoveField(
            model_name='company',
            name='salary',
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('experience', models.IntegerField(null=True)),
                ('Location', models.CharField(max_length=2000, null=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.company')),
            ],
        ),
    ]
