# Generated by Django 3.2.5 on 2021-08-31 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20210831_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='Location',
            new_name='location',
        ),
    ]
