# Generated by Django 3.2.5 on 2021-08-31 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_candidates_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='candidates',
            name='applied',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='posted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
